---
title: "Wordle"
author: "Ajna and Anais"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r wordle}
library(dplyr)
library(tidyverse)

words1<-"https://raw.githubusercontent.com/ajnafkertesz/ada-2022-datasets/main/collins-scrabble-words-2019.txt"


words2<-"https://raw.githubusercontent.com/ajnafkertesz/ada-2022-datasets/main/google-10000-english-usa-no-swears.txt"


##STEP 1
#create function to load dictionary

load_dictionary<-function(f){
  d<-read_csv(f, col_names = T)
  d<-d$words
  return(d)
}
  
valid_list<- load_dictionary(words1)
solution_list<-load_dictionary(words2)


#Note: How many 5-letter words are in each of the two data files you have downloaded?
summary(valid_list)
summary(solution_list)

# or View(valid_list)

str(valid_list)
str(solution_list)


##STEP 2

#select only words from solution_list that are include in Valid_list
solution_list<-intersect(valid_list,solution_list)

#Words in the updated solution_list
is.vector(solution_list)
str(solution_list)


##step 3

#create a function pick_solution() that
# [1] removes all words from solution_list that are not 5 letters in length, 
#[2] then randomly chooses a single word from those that remain, and 
#[3] then splits that word into a vector of single-character elements


pick_solution<-function(x,nchar){
    y<-nchar(x)
    w<-subset(x,y>nchar,drop=TRUE)
    z<-sample(w,1)
    strsplit(z,"")
}

solution <- pick_solution(solution_list,5)
solution



##Step 4
#create the play Wordle() function

play_wordle <- function(solution, valid_list, num_guesses=6){
  # pick a solution                                               #Anais to Ajna: we already have an answer selected with solution, no?                                                                      and solution as to be here since it is an argument of the function
  answer <- sample(valid_list, 1)
  answerVec <- strsplit(answer, "")[[1]]
  
      print(paste("You have",num_guesses,"chances to guess a word of length 5"))
  guessCnt <- 0
  lettersLeft <- toupper(LETTERS)
   while (guessCnt < nGuesses) {                  #Anais to Ajna: What is nGuesses, it is not define, we use num_guesses as argument
    # display "keyboard"
    print(paste(c("Letters left:", lettersLeft), collapse = " "))
     
 # read in guess
    guessCnt <- guessCnt + 1
    guess <- readline(paste0("Enter guess ", guessCnt, ": "))
    while (nchar(guess) != wordLength) {          #Anais to Ajna: WordLength is not defined here
      guess <- readline(paste0("Guess must have ", wordLength, " characters: "))
    }
    guess <- toupper(guess)
    guessVec <- strsplit(guess, "")[[1]]
    
    # update keyboard
    lettersLeft <- setdiff(lettersLeft, guessVec)
    
    # print result
    print(paste(strsplit(guess, "")[[1]], collapse = " "))
    print(paste(resVec, collapse = " "))
    if (all(resVec == "G")) {                                            ##Anais to Ajna: what is resVec
      print("You won!")
      return(guessCnt)
    }
  }
  print(paste("Sorry, you lost! Answer was ", answer)) ## should be solution too
  return(guessCnt)
}

play_wordle(valid_list)



#****************************
# ANAIS' TRY
#***************************

##Step 4
#create the play Wordle() function

play_wordle <- function(solution, valid_list, num_guesses=6){
  # pick a solution                                               #Anais to Ajna: change for solution as we defined it before
  solution <- pick_solution(solution_list,5)
  solution
  
      print(paste("You have",num_guesses,"chances to guess a word of length 5"))
  guessCnt <- 0
  lettersLeft <- toupper(LETTERS)
   while (guessCnt < num_guesses) {                  #Anais to Ajna: using num_guesses as argument
    # display "keyboard"
    print(paste(c("Letters left:", lettersLeft), collapse = " "))
     
 # read in guess
    guessCnt <- guessCnt + 1
    guess <- readline(paste0("Enter guess ", guessCnt, ": "))
    while (nchar(guess) != 5) {
      guess <- readline(paste0("Guess must have ", 5, " characters: ")) ## wordLenght was not defined, so to make it easy for now I changed it for 5
    }
    guess <- toupper(guess)
    guessVec <- strsplit(guess, "")[[1]]
    
    # update keyboard
    lettersLeft <- setdiff(lettersLeft, guessVec)
    
    # print result
    print(paste(strsplit(guess, "")[[1]], collapse = " "))
    print(paste(lettersLeft, collapse = " "))   ### added lettersleft here
    if (all(lettersLeft == "G")) {              ### added lettersleft here
      print("You won!")
      return(guessCnt)
    }
  }
  print(paste("Sorry, you lost! Answer was ", solution))
  return(guessCnt)
}

play_wordle(valid_list)



## 

























##Step 4
#create the play Wordle() function

play_wordle <- function(solution, valid_list, num_guesses=6){
  # Tell the rules of the game
  print(paste("You have",num_guesses,"chances to guess a word of length 5"))
  guessCnt <- 0
  lettersLeft <- toupper(LETTERS)
   while (guessCnt < num_guesses) {
    # display "keyboard"
    print(paste(c("Letters left:", lettersLeft), collapse = " "))

     #Prompt the player for a guess number
     
     
     
     
     
     
     
     
     
     
     
     
 # read in guess
    guessCnt <- guessCnt + 1
    guess <- readline(paste0("Enter guess ", guessCnt, ": "))
    while (nchar(guess) != wordLength) {
      guess <- readline(paste0("Guess must have ", wordLength, " characters: "))
    }
    guess <- toupper(guess)
    guessVec <- strsplit(guess, "")[[1]]
    
    # update keyboard
    lettersLeft <- setdiff(lettersLeft, guessVec)
    
    # print result
    print(paste(strsplit(guess, "")[[1]], collapse = " "))
    print(paste(resVec, collapse = " "))
    if (all(resVec == "G")) {
      print("You won!")
      return(guessCnt)
    }
  }
  print(paste("Sorry, you lost! Answer was ", answer))
  return(guessCnt)
}

play_wordle(valid_list)






```













